// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRuyOfGsqCUEwJSuiG9Ic6z_wBxxgivXU',
    appId: '1:1062587374774:android:0cc5e1a3780bed02229a17',
    messagingSenderId: '1062587374774',
    projectId: 'ourfitness-e3b7c',
    storageBucket: 'ourfitness-e3b7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kspAMmO17xIQM0eehRJQJq5OLSllVgc',
    appId: '1:1062587374774:ios:3e45ad9777b28413229a17',
    messagingSenderId: '1062587374774',
    projectId: 'ourfitness-e3b7c',
    storageBucket: 'ourfitness-e3b7c.firebasestorage.app',
    iosBundleId: 'com.example.imkOurfitness',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN3cm_CvenEkiM4YzBMEdKaFkZm74ZfPU',
    appId: '1:1062587374774:web:5b83293201a11be2229a17',
    messagingSenderId: '1062587374774',
    projectId: 'ourfitness-e3b7c',
    authDomain: 'ourfitness-e3b7c.firebaseapp.com',
    storageBucket: 'ourfitness-e3b7c.firebasestorage.app',
    measurementId: 'G-0KQKVZR4G8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kspAMmO17xIQM0eehRJQJq5OLSllVgc',
    appId: '1:1062587374774:ios:3e45ad9777b28413229a17',
    messagingSenderId: '1062587374774',
    projectId: 'ourfitness-e3b7c',
    storageBucket: 'ourfitness-e3b7c.firebasestorage.app',
    iosBundleId: 'com.example.imkOurfitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN3cm_CvenEkiM4YzBMEdKaFkZm74ZfPU',
    appId: '1:1062587374774:web:cf0b67e809ee66f5229a17',
    messagingSenderId: '1062587374774',
    projectId: 'ourfitness-e3b7c',
    authDomain: 'ourfitness-e3b7c.firebaseapp.com',
    storageBucket: 'ourfitness-e3b7c.firebasestorage.app',
    measurementId: 'G-D976JXEX2F',
  );

}